version: '3'
services:
  rails:
    build: .
    command: bash -c "bundle install && rails s -b 0.0.0.0"
    container_name: study-smart
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment:
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - study-smart_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  study-smart_data: