version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: study-smart
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment: 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - study-smart_data:/var/lib/mysql
volumes:
  study-smart_data: